Repository OZblind/OZblind_FE, pull requests merged in 2025-08, with the labels that each got.

#35 [feat] 로그인/회원가입 페이지(로비 페이지) 로직 작업
  .env
  docs/How-to-use-Toast.md
  docs/How-to-use-authStore.md
  package-lock.json
  package.json
  src/App.tsx
  src/api/api.md
  src/api/auth.ts
  src/api/client.md
  src/api/client.ts
  src/assets/images/error-toast.svg
  src/assets/images/info-toast.svg
  src/assets/images/success-check.png
  src/assets/images/success-toast.svg
  src/assets/images/warning-toast.svg
  src/components/commons/Toast/Toast.tsx
  src/constants/constants.md
  src/constants/endpoints.ts
  src/constants/paths.ts
  src/constants/queryKeys.ts
  src/hooks/useAuthBootstrap.ts
  src/hooks/useAuthQueries.ts
  src/index.css
  src/layouts/RootLayout.tsx
  src/main.tsx
  src/pages/landing/LandingPage.tsx
  src/pages/main/MainPage.tsx
  src/pages/test/HSYtestpage.tsx
  src/pages/test/TestHub.tsx
  src/router/AppRouter.tsx
  src/router/guards.tsx
  src/store/authStore.ts
  src/store/toastStore.ts
  src/utils/auth/events.ts
  src/utils/auth/sync.ts
  src/utils/google.ts
  src/utils/pickFirst.ts
  src/utils/postLogin.ts
  src/utils/routerIntent.ts
  vercel.json
Labels: documentation, enhancement

#41 Feature/39 sp post editor
  .hintrc
  src/components/Board/SharedPostForm.tsx
  src/components/Board/SurveyPostForm.tsx
  src/components/Board/WritePostPage.tsx
  src/components/Board/editor/ToastEditor.tsx
  src/main.tsx
Labels: enhancement

#56 [feat] useInfiniteScroll 훅 (IntersectionObserver)
  docs/How-to-use-useInfiniteScroll.md
  src/components/commons/InfiniteScroll/ScrollSentinel.tsx
  src/hooks/useInfiniteScroll.ts
  src/hooks/useResponsivePageSize.ts
  src/pages/test/TestHub.tsx
  src/pages/test/TestInfiniteScroll.tsx
Labels: documentation, enhancement

#57 [feat] 사용자 설정 모달 UI 컴포넌트 구현
  index.html
  src/components/commons/SettingModal/AccountDeletionSection.tsx
  src/components/commons/SettingModal/KeySection.tsx
  src/components/commons/SettingModal/SettingsPage.tsx
  src/components/commons/SettingModal/SettingsPopup.tsx
  src/components/commons/SettingModal/ThemeInitializer.tsx
  src/components/commons/SettingModal/ThemeToggleSection.tsx
  src/pages/test/TestHub.tsx
  src/pages/test/TestSettingPage.tsx
  src/router/AppRouter.tsx
  src/utils/themeInit.ts
Labels: enhancement

#62 [feat] 자유·취업·정보 게시판 리스트 본문 UI
  src/components/Board/common/BoardTopBar.tsx
  src/components/Board/common/EmptyState.tsx
  src/components/Board/common/FilterIconButton.tsx
  src/components/Board/common/LastLoadedBar.tsx
  src/components/Board/common/WriteButton.tsx
  src/components/Board/free/PostCard.tsx
  src/components/Board/free/PostList.tsx
  src/components/Board/free/PostRow.tsx
  src/components/SettingModal/AccountDeletionSection.tsx
  src/components/SettingModal/KeySection.tsx
  src/components/SettingModal/SettingsPage.tsx
  src/components/SettingModal/SettingsPopup.tsx
  src/components/SettingModal/ThemeInitializer.tsx
  src/components/SettingModal/ThemeToggleSection.tsx
  src/pages/test/BoardList/TestFreeBoardList.tsx
  src/pages/test/TestHub.tsx
  src/pages/test/TestSettingPage.tsx
  src/router/AppRouter.tsx
  src/utils/date.ts
  tailwind.config.js
Labels: enhancement

#64 [feat] Sidebar 컴포넌트 UI 구현
  src/assets/images/profile.jpg
  src/components/Sidebar/LogoutSection.tsx
  src/components/Sidebar/PostListSection.tsx
  src/components/Sidebar/ProfileSection.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarFolded.tsx
  src/components/Sidebar/SidebarOpen.tsx
  src/components/Sidebar/SmallProfileSection.tsx
  src/pages/test/TestHub.tsx
  src/pages/test/TestMainPage.tsx
  src/router/AppRouter.tsx
Labels: enhancement

#76 Feature/75 apply tags
  docs/How-to-use-TagBadge.md
  src/components/Post/PostDetail.tsx
  src/components/Sidebar/ProfileSection.tsx
  src/components/Sidebar/SmallProfileSection.tsx
  src/components/tags/AssignedTagList.tsx
  src/components/tags/TagBadge.tsx
  src/mocks/post.demo.ts
Labels: enhancement

#74 Feature/73 random nick
  src/api/nickname.ts
  src/components/Post/PostDetail.tsx
  src/components/Post/comments/PostComment.tsx
  src/constants/easterEggNicknames.ts
Labels: enhancement

#81 Feature/77 job banner
  .gitignore
  src/api/jobs/arbeitnow.ts
  src/api/jobs/ashby.ts
  src/api/jobs/index.ts
  src/api/jobs/remoteok.ts
  src/components/JobBanner/Carousel.tsx
  src/components/JobBanner/CompanyLogo.tsx
  src/components/JobBanner/JobBannerTabs.tsx
  src/components/JobBanner/LeftTabs.tsx
  src/hooks/useJobs.ts
  src/pages/test/TestHub.tsx
  src/pages/test/TestJobBanner.tsx
  src/router/AppRouter.tsx
  src/types/job.ts
Labels: enhancement

#94 [fix] Hot 게시판 조회수 삭제
  src/components/HotBoard/HotBoard.tsx
  src/components/HotBoard/HotPostCard.tsx
  src/components/HotBoard/data.ts
Labels: bug

#95 [feat] GitHub 게시판 카드 리스트 본문 UI (GitHub 게시글 카드 포함)
  src/components/Board/github/GithubCard.tsx
  src/components/Board/github/GithubList.tsx
  src/components/Board/github/RepoPreviewThumb.tsx
  src/components/Board/github/index.ts
  src/hooks/useGithubPosts.mock.tsx
  src/pages/test/BoardList/TestGithubList.tsx
  src/pages/test/TestHub.tsx
  src/router/AppRouter.tsx
Labels: enhancement

#102 [feat] 정렬 필터 UI (최신/추천/조회/댓글) - 라디오 버튼
  src/components/Board/common/BoardTopBar.tsx
  src/components/Board/common/FilterIconButton.tsx
  src/components/Board/common/sort/SortRadio.tsx
  src/components/Board/common/sort/SortRadioPopover.tsx
  src/components/Board/free/PostList.tsx
  src/components/Board/github/GithubList.tsx
  src/components/Board/survey/SurveyList.tsx
  src/types/sort.ts
Labels: enhancement

#134 [feat] 메인 레이아웃에 마이페이지 추가
  src/constants/paths.ts
  src/pages/mypage/MyPageMain.tsx
  src/router/AppRouter.tsx
Labels: enhancement

#136 [feat] 자유/취업/정보 게시판 페이지 API 추가된 컴포넌트와 합성
  src/api/posts.ts
  src/components/Board/common/WriteButton.tsx
  src/components/Board/free/PostList.tsx
  src/constants/board.ts
  src/constants/boards.ts
  src/constants/easterEggNicknames.ts
  src/constants/ui.ts
  src/hooks/useBoardPosts.ts
  src/mocks/useBoardPosts.mock.ts
  src/pages/boards/FreeBoard.tsx
  src/pages/boards/InfoBoard.tsx
  src/pages/boards/JobsBoard.tsx
  src/pages/boards/PostDetailPage.tsx
  src/pages/boards/PostListPage.tsx
  src/pages/test/TestHub.tsx
  src/router/AppRouter.tsx
  src/types/search.ts
  src/types/sort.ts
  src/utils/tagsToAuthorLabel.ts
Labels: enhancement

#142 [fix] 취업 게시판 - 정보 게시판 경로 꼬임
  src/components/Post/PostDetail.tsx
  src/pages/boards/PostDetailPage.tsx
  src/router/AppRouter.tsx
Labels: bug

#183 Feature/128 api comment
  .hintrc
  src/api/comments.ts
  src/components/Post/PostDetail.tsx
  src/components/Post/comments/CommentItem.tsx
  src/components/Post/comments/PostComment.tsx
  src/components/Post/comments/ReplyControl.tsx
  src/hooks/useComments.ts
  src/types/comment.ts
  src/utils/comments.ts
Labels: api

#190 [fix] 설문/깃헙 게시판에서 상세페이지로 넘어가는 경로 설정
  src/pages/boards/GithubListPage.tsx
  src/pages/boards/SurveyListPage.tsx
Labels: bug

#201 [feat] 게시글 상세 페이지 타이틀 수정
  src/components/Post/PostDetail.tsx
  src/constants/boardDisplay.ts
  src/mocks/post.demo.ts
  src/pages/boards/PostDetailPage.tsx
  src/types/post.ts
Labels: enhancement

#209 [fix] 회원 탈퇴 시 페이지 리다이렉트
  src/components/SettingModal/AccountDeletionSection.tsx
Labels: bug

#218 [feat] 태그 필터 로직 구현, API 연결
  src/api/posts.ts
  src/components/Board/common/tagfilter/TagFilterPopover.tsx
  src/components/Board/free/PostList.tsx
  src/components/Board/github/GithubList.tsx
  src/components/Board/survey/SurveyList.tsx
  src/features/tags/adapters.ts
  src/features/tags/queryMap.ts
  src/hooks/useBoardPosts.ts
  src/hooks/useGithubPosts.ts
  src/hooks/useSurveys.ts
  src/pages/boards/GithubListPage.tsx
  src/pages/boards/PostListPage.tsx
  src/pages/boards/SurveyListPage.tsx
  src/types/tag.ts
  src/utils/tagRules.ts
Labels: enhancement, api

#219 [feat] 맨 위로 가기 버튼 UI 컴포넌트 구현 및 적용
  src/components/Board/free/PostList.tsx
  src/components/commons/ScrollToTop/EnsureDefaultScrollRoot.tsx
  src/components/commons/ScrollToTop/LockOutletScrollWhenChildRoot.tsx
  src/components/commons/ScrollToTop/OutletWithScrollToTop.tsx
  src/components/commons/ScrollToTop/ScrollRootProvider.tsx
  src/components/commons/ScrollToTop/ScrollToTopButton.tsx
  src/components/commons/ScrollToTop/index.ts
  src/components/commons/ScrollToTop/scroll-root-store.ts
  src/components/commons/ScrollToTop/useScrollRoot.ts
  src/layouts/MainLayout.tsx
  src/pages/boards/GithubListPage.tsx
  src/pages/boards/PostListPage.tsx
  src/pages/boards/SurveyListPage.tsx
Labels: enhancement

#204 [feat] Hot 게시판 API 연결
  src/api/client.ts
  src/api/hotPosts.ts
  src/components/HotBoard/HotBoard.tsx
  src/components/HotBoard/HotPostCard.tsx
  src/components/HotBoard/boardColor.ts
  src/pages/main/MainPage.tsx
  src/pages/test/TestMainPage.tsx
  src/router/AppRouter.tsx
  src/types/hotPost.ts
Labels: api

#227 [feat] 테스트 허브 라우트 삭제 및 키인증 팝업 API 연결
  src/api/auth.ts
  src/components/SettingModal/AccountDeletionSection.tsx
  src/components/SettingModal/KeySection.tsx
  src/components/SettingModal/SettingsPopup.tsx
  src/constants/paths.ts
  src/router/AppRouter.tsx
Labels: enhancement, api

#158 Feat/156 search page & api
  package-lock.json
  package.json
  src/api/searchApi.ts
  src/components/Board/free/PostRow.tsx
  src/components/commons/MyPage/PageHeader.tsx
  src/constants/endpoints.ts
  src/hooks/useSearchLogic.ts
  src/pages/boards/SearchPage.tsx
  src/pages/test/BoardList/TestFreeBoardList.tsx
  src/pages/test/BoardList/TestGithubList.tsx
  src/pages/test/BoardList/TestSurveyList.tsx
  src/pages/test/TestHub.tsx
  src/router/AppRouter.tsx
  src/types/search.ts
  src/utils/urlForPost.ts
Labels: enhancement, api
